[project]
name = "mock"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cryptography>=45.0.4",
    "faker>=37.4.0",
    "pymysql>=1.1.1",
]
